name: Automated Test

on:
  push:
    branches:
      - main
      - continuous-_integration

jobs:
  run-tests: 
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
      - name: Start FEniCS and run tests
        run: docker run -v $(pwd):/home/fenics/shared quay.io/fenicsproject/stable -i python3 -m unittest coupling_test
  

